# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a64323ca7812bedaa4fd486ced58b7b85ec03a8aa31c6b57ab9c47db9fdf6438672e6ecf0fb3cfe87daf96c7fc8dedbb6b8e417989f241dcb85693b93d47691

test:
  secret_key_base: d70b841e40d737c1943f4e3ea5f3973ec7aefea8d6f4ee0f8a0d84ed08d7f68d7b01a8cbe55fca5a8a2ff5757cc52d1b1f9b4305d0853032bf5fc58fa9351082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
